// This file is automatically generated by Next.js
// Do not edit this file manually
// See: https://nextjs.org/docs/app/api-reference/config/typescript for more information.

/// <reference types="next" />
/// <reference types="next/image-types/global" />
