import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const configPath = path.join(rootDir, "business.config.ts");

export interface InitAnswers {
  name: string;
  tagline: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  timezone: string;
  serviceName: string;
  serviceDescription: string;
  servicePriceFrom?: number;
  brandColor: string;
}

export function generateConfigFileContent(answers: InitAnswers): string {
  const serviceSlug = answers.serviceName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  const priceLine =
    typeof answers.servicePriceFrom === "number" && !Number.isNaN(answers.servicePriceFrom)
      ? `priceFrom: ${answers.servicePriceFrom},`
      : "";

  return `import { parseBusinessConfig, type BusinessConfig } from "./lib/config";

/**
 * Generated by \`npm run init\`.
 * Validated against \`lib/config.ts\` zod schema at build time and dev startup.
 */
const rawConfig = {
  name: ${JSON.stringify(answers.name)},
  tagline: ${JSON.stringify(answers.tagline)},
  businessType: "other",
  siteUrl: "https://example.com",
  logoPath: "/logo.svg",
  description: ${JSON.stringify(
    `${answers.name} provides trusted professional services in ${answers.city}, ${answers.state}.`
  )},

  address: {
    street: ${JSON.stringify(answers.street)},
    city: ${JSON.stringify(answers.city)},
    state: ${JSON.stringify(answers.state)},
    zip: ${JSON.stringify(answers.zip)},
    country: "US",
  },
  phone: ${JSON.stringify(answers.phone)},
  email: ${JSON.stringify(answers.email)},
  geo: {
    lat: 40.7128,
    lng: -74.006,
  },
  timezone: ${JSON.stringify(answers.timezone || "America/New_York")},

  hours: {
    mon: { closed: false, ranges: [{ open: "09:00", close: "17:00" }] },
    tue: { closed: false, ranges: [{ open: "09:00", close: "17:00" }] },
    wed: { closed: false, ranges: [{ open: "09:00", close: "17:00" }] },
    thu: { closed: false, ranges: [{ open: "09:00", close: "17:00" }] },
    fri: { closed: false, ranges: [{ open: "09:00", close: "17:00" }] },
    sat: { closed: true },
    sun: { closed: true },
  },

  theme: {
    preset: "neutral",
    brandColor: ${JSON.stringify(answers.brandColor || "#2563eb")},
  },

  services: [
    {
      slug: ${JSON.stringify(serviceSlug || "general-service")},
      name: ${JSON.stringify(answers.serviceName)},
      description: ${JSON.stringify(answers.serviceDescription)},
      ${priceLine}
    },
  ],

  testimonials: [
    {
      quote:
        "Outstanding service and incredible attention to detail. Highly recommend to anyone in our area!",
      name: "Alex Morgan",
      town: ${JSON.stringify(answers.city)},
      rating: 5,
    },
  ],

  serviceAreas: [${JSON.stringify(answers.city)}],

  faq: [
    {
      question: "How do I book an appointment?",
      answer: "Give us a call or visit our contact page to get started.",
    },
    {
      question: "Are you licensed and insured?",
      answer: "Yes, fully licensed, certified, and insured for your peace of mind.",
    },
  ],

  images: {
    hero: "/images/hero.jpg",
  },

  sections: [
    { type: "hero", variant: "split-image" },
    { type: "services", variant: "grid-cards" },
    { type: "testimonials", variant: "grid-cards" },
    { type: "serviceArea", variant: "pill-cloud" },
    { type: "hoursContact", variant: "card" },
    { type: "faq", variant: "accordion" },
    { type: "ctaBand", variant: "simple" },
  ],
} as const;

export const businessConfig: BusinessConfig = parseBusinessConfig(rawConfig);
export default businessConfig;
`;
}

export async function runInitCLI() {
  const rl = readline.createInterface({ input, output });

  console.log("\n--- LocalBiz Site Initializer ---\n");

  if (fs.existsSync(configPath)) {
    const existingContent = fs.readFileSync(configPath, "utf-8");
    if (!existingContent.includes("Maple Street Plumbing")) {
      const confirmOverwrite = await rl.question(
        "A customized business.config.ts already exists. Overwrite? (y/N): "
      );
      if (confirmOverwrite.trim().toLowerCase() !== "y") {
        console.log("Initialization aborted. Existing config preserved.\n");
        rl.close();
        return;
      }
    }
  }

  const name = (await rl.question("Business Name (e.g. Acme Studio): ")).trim() || "Acme Studio";
  const tagline =
    (await rl.question("Tagline (e.g. Quality service you can trust): ")).trim() ||
    "Quality service you can trust";
  const street = (await rl.question("Street Address: ")).trim() || "100 Main Street";
  const city = (await rl.question("City: ")).trim() || "New York";
  const state = (await rl.question("State / Province (e.g. NY): ")).trim() || "NY";
  const zip = (await rl.question("Zip / Postal Code: ")).trim() || "10001";
  const phone = (await rl.question("Phone Number: ")).trim() || "(555) 123-4567";
  const email = (await rl.question("Email Address: ")).trim() || "contact@example.com";
  const timezone = (await rl.question("Timezone (default: America/New_York): ")).trim() || "America/New_York";
  const brandColor = (await rl.question("Brand Hex Color (default: #2563eb): ")).trim() || "#2563eb";

  console.log("\nFirst Service offering:");
  const serviceName = (await rl.question("Service Name (e.g. Standard Consultation): ")).trim() || "Standard Consultation";
  const serviceDescription =
    (await rl.question("Service Description: ")).trim() ||
    "Comprehensive service and professional consultation.";
  const priceInput = (await rl.question("Starting Price (optional, e.g. 99): ")).trim();
  const servicePriceFrom = priceInput ? Number(priceInput) : undefined;

  rl.close();

  const answers: InitAnswers = {
    name,
    tagline,
    street,
    city,
    state,
    zip,
    phone,
    email,
    timezone,
    brandColor,
    serviceName,
    serviceDescription,
    servicePriceFrom: Number.isNaN(servicePriceFrom) ? undefined : servicePriceFrom,
  };

  const newConfig = generateConfigFileContent(answers);
  fs.writeFileSync(configPath, newConfig, "utf-8");

  console.log("\nSuccessfully generated business.config.ts!");
  console.log("Run `npm run typecheck` or `npm run build` to verify.\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runInitCLI().catch((err) => {
    console.error("Initialization error:", err);
    process.exit(1);
  });
}
